version: "3.9"

services:
  postgres_db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prisma
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prisma-network

  prisma-init:
    build:
      context: ./prisma
      dockerfile: Dockerfile
    env_file:
      - ./prisma/.env
    depends_on:
      - postgres_db
    # mount host folders so Prisma can write into them
    volumes:
      - "./prisma:/app" # schema + .env
      - "./front_end/src/prisma:/front_end/src/prisma" # JS client
      - "./back_end/prisma_client_py:/back_end/prisma_client_py" # Py client
    # run generation & push at startup
    entrypoint: [
        "sh",
        "-c",
        "prisma generate --schema=./schema.prisma && \
        python3 -m prisma generate --schema=./schema.prisma && \
        prisma db push --schema=./schema.prisma && \
        echo ✅ Prisma clients+schema done && sleep infinity",
      ]
    networks:
      - prisma-network

  app:
    build:
      context: ./back_end
      dockerfile: Dockerfile
    env_file:
      - ./back_end/.env
    depends_on:
      prisma-init:
        condition: service_healthy
      postgres_db:
        condition: service_healthy
    ports:
      - "8000:80"
    volumes:
      - "./back_end/app:/app/app:ro"
      - "./back_end/prisma_client_py:/app/prisma:ro"
    environment:
      - PYTHONPATH=/app
    networks:
      - prisma-network

  frontend-dev:
    build:
      context: ./front_end
      dockerfile: Dockerfile
    depends_on:
      - prisma-init
      - postgres_db
    ports:
      - "3000:3000"
    volumes:
      - "./front_end:/app"
      - "./prisma:/app/prisma:ro"
      - "./front_end/src/prisma:/app/src/prisma:ro"
    environment:
      - DATABASE_URL=postgresql://postgres:prisma@postgres_db:5432/postgres
    networks:
      - prisma-network

  prisma-studio:
    build:
      context: ./prisma
      dockerfile: Dockerfile
    env_file:
      - ./prisma/.env
    depends_on:
      - prisma-init
      - postgres_db
    command: >
      prisma studio --schema=./schema.prisma --port=5555 --browser none
    ports:
      - "5555:5555"
    volumes:
      - "./prisma:/app"
    networks:
      - prisma-network

volumes:
  postgres_data:

networks:
  prisma-network:
    driver: bridge
