version: "3.9"

services:
  # ──────────────────────────────────────────────────────────────
  # 1) PostgreSQL
  # ──────────────────────────────────────────────────────────────
  postgres_db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prisma
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20
    networks:
      - prisma-network

  # ──────────────────────────────────────────────────────────────
  # 2) FastAPI backend (Python Prisma)
  # ──────────────────────────────────────────────────────────────
  back_end:
    build:
      context: ./back_end
      dockerfile: Dockerfile
    env_file:
      - ../prisma/.env
    depends_on:
      - postgres_db
    ports:
      - "8000:80"
    volumes:
      - "./back_end/app:/app/app:ro"
      # ONLY mount the actual Prisma package, not the entire generator folder:
      - "./back_end/prisma_client_py/prisma:/app/prisma:ro"
    environment:
      - PYTHONPATH=/app
    networks:
      - prisma-network

  # ──────────────────────────────────────────────────────────────
  # 3) Next.js frontend (JS Prisma)
  # ──────────────────────────────────────────────────────────────
  front_end:
    build:
      context: ./front_end
      dockerfile: Dockerfile
    env_file:
      - ../prisma/.env
    depends_on:
      - postgres_db
    ports:
      - "3000:3000"
    volumes:
      - "./front_end:/app"
      - "./front_end/src/prisma:/app/src/prisma:ro"
    environment:
      - DATABASE_URL=postgresql://postgres:prisma@postgres_db:5432/postgres
    networks:
      - prisma-network

  # ──────────────────────────────────────────────────────────────
  # 4) Prisma Studio
  # ──────────────────────────────────────────────────────────────
  prisma-studio:
    build:
      context: ./prisma
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - postgres_db
    entrypoint:
      - sh
      - -c
      - prisma studio --schema=./schema.prisma --port=5555 --browser none
    ports:
      - "5555:5555"
    volumes:
      - "./prisma:/app"
    networks:
      - prisma-network

networks:
  prisma-network:
    driver: bridge
