from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'User',
    'Response',
    'Category',
    'Pattern',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'User': {
        'responses': 'Response',
    },
    'Response': {
        'categories': 'Category',
        'user': 'User',
    },
    'Category': {
        'patterns': 'Pattern',
        'response': 'Response',
    },
    'Pattern': {
        'category': 'Category',
    },
}

# fmt: on